name: bunnie
description: A new Flutter project.

version: 0.2.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  asuka: ^2.0.0+3
  dartz: ^0.10.1
  flutter_spinkit: ^5.1.0
  simple_animations: ^5.0.0+3
  font_awesome_flutter: ^10.4.0
  #share: ^2.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  dio: ^5.0.0
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3+1
  flutter_modular: ^5.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.5.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight-slnt=0.ttf
          weight: 100
        - asset: assets/fonts/Inter-Thin-slnt=0.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light-slnt=0.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular-slnt=0.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium-slnt=0.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold-slnt=0.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold-slnt=0.ttf
          weight: 700
        - asset: assets/fonts/Inter-Black-slnt=0.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraBold-slnt=0.ttf
          weight: 900

scripts:
  build: flutter pub run build_runner build
  build_delete: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
  emulator: flutter emulators --launch Pixel_3a_API_30_x86
